### ISSUE TITLE
structure des fichiers d'icônes

### ISSUE THREAD

**Issue by gnoubi** [LittoSim/LittoSim_model#19]
modifier la structure des fichiers d'icônes afin de séparer les icônes modifiables des icônes systèmes
deux dossiers sont envisagés 
- system-icons
- developer-icons

**Comment by Damapproject** [comment]
#https://github.com/LittoSim/LittoSim_model/commit/e83c219255b4c09819bb83c4f0e6526c7797e955

**Comment by nbecu** [comment]
C'est bien rangé  et c'est beaucoup plus clair à présent, Bravo
