### ISSUE TITLE
ajouter une horloge

### ISSUE THREAD

**Issue by gnoubi** [LittoSim/LittoSim_model#23]
ajouter une horloge sur l'interface partagée (la carte affichée à tous sur le serveur)

**Comment by Damapproject** [comment]
Une horloge affiche sur le display de submersion, le nombre d'heures et de minutes écoulées à chaque itération.
https://github.com/LittoSim/LittoSim_model/commit/362494d4fb7a23b43c77a0dd968fef929585fed0
