### ISSUE TITLE
study-area.conf Urban ring

### ISSUE THREAD

**Issue by gnoubi** [LittoSim/LittoSim_model#25]
laisser la possibilité de mettre en commentaire le paramètre "urban-ring"

**Comment by Damapproject** [comment]
Si le paramètre URBAN_RING n'est pas spécifié, ou s'il est mis à zéro, on peut urbaniser à tout endroit possible, même en dehors du cercle urbain.
#https://github.com/LittoSim/LittoSim_model/commit/c6deec3e1d19a512c95caef6f1e92f798d2c91c0
