### ISSUE TITLE
lever.conf

### ISSUE THREAD

**Issue by gnoubi** [LittoSim/LittoSim_model#27]
Le fichier lever.conf est à transférer dans le fichier de langue général

**Comment by nbecu** [comment]
Ou plutôt, les paramètres de langue du fichier lever.conf sont à
transférer  dans le fichier de langue général

Le jeu. 28 mai 2020 à 13:01, Nicolas Marilleau <notifications@github.com> a
écrit :

**Comment by Damapproject** [comment]
#https://github.com/LittoSim/LittoSim_model/commit/1540af0e0d5b37178868009ce073d692d6a4c087
