### ISSUE TITLE
grille de rugosité 

### ISSUE THREAD

**Issue by gnoubi** [LittoSim/LittoSim_model#31]
simplifier le xml car la taille et la précision peuvent être lu dans le fichier contenant la grille de rugosité

**Comment by Damapproject** [comment]
Les dimensions et la résolution de la grille de rugosité sont directement lus à partir du MNT et pas besoin de les fournir dans le fichier XML de mapping.
https://github.com/LittoSim/LittoSim_model/commit/64238bc2b29e95e0851b4c78444b87e833d18cb4
