### ISSUE TITLE
Ajouter un fichier CSV pour Manning

### ISSUE THREAD

**Issue by gnoubi** [LittoSim/LittoSim_model#32]
celui qui parle du coef de Manning pour être en mesure de customiser la rugosité

**Comment by Damapproject** [comment]
Toutes les valeurs de rugosité possibles sont dans un fichier csv "**clc_manning.csv**"  qui est lu par le script pour remplacer les valeurs présentes dans le fichier CLC "land_cover.shp".

https://github.com/LittoSim/LittoSim_model/commit/3a1abcf2100c97b659af072a334d50d9aed70c6f
