### ISSUE TITLE
vérifier dans le modèle que lisflood est correctement installé

### ISSUE THREAD

**Issue by gnoubi** [LittoSim/LittoSim_model#37]
Il s'agirait d'ajouter d'afficher une erreur au lancement du modèle afin de savoir si lisflood est correctement installé

il faudrait tester de l'existence du fichier

**Comment by Damapproject** [comment]
#https://github.com/LittoSim/LittoSim_model/commit/9e7ba0c7bc9b54e0c04915dbbf57a6a7e215e940
