### ISSUE TITLE
enhancement du code pour une prise en compte plus générique du paramètre STEPS_FOR_AU_TO_U; 

### ISSUE THREAD

**Issue by nbecu** [LittoSim/LittoSim_model#42]
permettre que si 
STEPS_FOR_AU_TO_U; est 0, dans ce cas le LU ne passe pas par un stade de AU, mais passe directement en U

**Comment by Damapproject** [comment]
Si _STEPS_FOR_AU_TO_U_ = 0, les états AU et AUs sont omits, la cellule passe directement à U/Us avec une population égale à _POP_FOR_NEW_U_.
#https://github.com/LittoSim/LittoSim_model/commit/52569c6299bf124efb24a69b8295ea9783a08137
