### ISSUE TITLE
créer des fichiers de symbologie pour l'affichage des résultats (raster et shp) (en ArcGIS et QGIS)

### ISSUE THREAD

**Issue by nbecu** [LittoSim/LittoSim_model#49]

**Comment by ceciliapm** [comment]
[lyr.zip](https://github.com/LittoSim/LittoSim_model/files/4736847/lyr.zip)
[qml.zip](https://github.com/LittoSim/LittoSim_model/files/4736848/qml.zip)
[readme.txt](https://github.com/LittoSim/LittoSim_model/files/4736849/readme.txt)

**Comment by Damapproject** [comment]
Les nouveaux fichiers de symbologie sont dans https://github.com/LittoSim/LittoSim_model/tree/LittoDev/Rscripts/post_processing/symbologie
