### ISSUE TITLE
permettre de spécifier le nom qu'on veut pour le titre des communes

### ISSUE THREAD

**Issue by nbecu** [LittoSim/LittoSim_model#53]

**Comment by nbecu** [comment]
Est ce que cette issue se rapporte au nom qui s'affiche dans les interfaces des modèles Gama , ou est -ce que c'est à propos des noms utilisés dans le Script R ?

**Comment by Damapproject** [comment]
C'est par rapport aux graphes R, et c'est résolu.
#https://github.com/LittoSim/LittoSim_model/commit/d0fc5f94ea8fce7faa28ed4d06b6b0b2dca561d5

Pour l'interface GAMA, les noms utilisés sont les longs names dans le study_area.conf.
