### ISSUE TITLE
Mettre le LongName des communes dans certaines des interfaces Gama

### ISSUE THREAD

**Issue by nbecu** [LittoSim/LittoSim_model#57]
Dans certaines des interafecs GAMA c'est le SNAME qui est utilisé alors qu'on fait il y a la place pour mettre le LongNAme.  Peut on remplacer svp ?
1/
![image](https://user-images.githubusercontent.com/7630183/83648390-49434e00-a5b6-11ea-9386-d2d65a737eba.png)
Dans cette interface on peut d'ailleurs enlever le terme "District" et mettre tout de suite la valleur du LongName

2/
![image](https://user-images.githubusercontent.com/7630183/83648618-8c9dbc80-a5b6-11ea-9169-51d8caa3fc87.png)
3/
![image](https://user-images.githubusercontent.com/7630183/83648692-a2ab7d00-a5b6-11ea-9b63-b74e93137573.png)

**Comment by Damapproject** [comment]
Désormais c'est les noms longs (_MAP_DIST_LNAMES_) qui s'affichent sur toutes les interfaces, même si on peut pas voir les noms complets sur quelques graphes ..
#https://github.com/LittoSim/LittoSim_model/commit/545d3ae68b3bb3b6cd1634787cbd6f308c20778a
