### ISSUE TITLE
problème mise à jour du budget des communes

### ISSUE THREAD

**Issue by nbecu** [LittoSim/LittoSim_model#58]
J'ai changé le SNAME et le LNAME de la commune B, et depuis le budget de la commune n'est pas actualisé à chaque tour

**Comment by Damapproject** [comment]
Non, en effet MAP_DIST_LNAMES servent à l'affichage uniquement, et on peut les changer librement. Les noms dans MAP_DIST_SNAMES servent à identifier les communes, et on peut également les changer librement, sans oublier de les changer aussi dans IMPOT_UNIT_TABLE (c'est de là forcément que vient ton problème de budgets).
Les noms dans MAP_DIST_SNAMES et IMPOT_UNIT_TABLE doivent être les mêmes.
