### ISSUE TITLE
rendre paramétrable la restriction de construire dans les zones protégées

### ISSUE THREAD

**Issue by nbecu** [LittoSim/LittoSim_model#60]
Peut on avoir un paramètre qui permettrait d'enlever la restriction de construire dans les zones protégées ?

On aurai plus alors cette fenetre qui apparaitrait
![image](https://user-images.githubusercontent.com/7630183/83661075-ee195780-a5c5-11ea-9a3f-6d40541b75de.png)

-----  
par défaut le paramètre serai que la restriction est active

**Comment by Damapproject** [comment]
Action done #https://github.com/LittoSim/LittoSim_model/commit/f2543145642159acb5d0687f24507d440eedbf81
