### ISSUE TITLE
Erreur colonne "round_delay" fichier player actions

### ISSUE THREAD

**Issue by ameliemft** [LittoSim/LittoSim_model#75]
J'ai remarqué dans les fichiers player_actions des ateliers de Camargue et de Rochefort que la colonne "round_delay" indique systématiquement 0 pour tous les types d'actions, même celles labelisées expropriation qui normalement prennent plusieurs tours. Peut-on résoudre ce bug ?

Cf ex fichiers Camargue et Rochefort
[Player actions Camargue 10-12-2019.xlsx](https://github.com/LittoSim/LittoSim_model/files/5987643/Player.actions.Camargue.10-12-2019.xlsx)
[player_actions_round3.xlsx](https://github.com/LittoSim/LittoSim_model/files/5987649/player_actions_round3.xlsx)

**Comment by Damapproject** [comment]
Bonjour Amélie,
"round_delay" ne signifie pas le nombre de tours que prennent l'action (qui
est fixé dans le fichier actions.conf), mais le nombre de tours du retard
si l'action est retardée par un levier. Donc la colonne sera différente de
0 uniquement si un "delay lever" est appliqué sur l'action.

**Comment by ameliemft** [comment]
Ah d'accord je comprends mieux ! Désolée pour l'erreur, merci !
